const luzon = [
    {
        title: "3BR Prime House & Lot",
        floorArea: "300sqm",
        lotArea: "200sqm",
        location: "Angeles, Pampanga",
        price: "Php 3,450,000.00",
        image: "images/luzon/luzon1.jpg",
        href: "properties/luzon1.html",
    },
    {
        title: "3BR Bungalow House & Lot",
        floorArea: "150sqm",
        lotArea: "250sqm",
        location: "Gen. Trias, Cavite",
        price: "Php 4,250,000.00",
        image: "images/luzon/luzon2.jpg",
        href: "properties/luzon2.html",
    },
    {
        title: "2BR 2-storey House & Lot",
        floorArea: "250sqm",
        lotArea: "150sqm",
        location: "Trece Martirez, Cavite",
        price: "Php 5,150,000.00",
        image: "images/luzon/luzon3.jpg",
        href: "properties/luzon3.html",
    },
    {
        title: "2BR Prime Condominium",
        floorArea: "150sqm",
        lotArea: "N/A",
        location: "Makati City, Metro Manila",
        price: "Php 10,000,000.00",
        image: "images/luzon/luzon4.jpg",
        href: "properties/luzon4.html",
    },
    {
        title: "1BR Loft-type Condominium",
        floorArea: "60sqm",
        lotArea: "N/A",
        location: "Mandaluyong, Metro Manila",
        price: "Php 3,299,000.00",
        image: "images/luzon/luzon5.jpg",
        href: "properties/luzon5.html",
    },
    {
        title: "2BR Corner House & Lot",
        floorArea: "300sqm",
        lotArea: "450sqm",
        location: "Dagupan, Pangasinan",
        price: "Php 4,450,000.00",
        image: "images/luzon/luzon6.jpg",
        href: "properties/luzon6.html",
    },
    {
        title: "2BR 2-storey House & Lot",
        floorArea: "250sqm",
        lotArea: "175sqm",
        location: "Balanga, Bataan",
        price: "Php 3,950,000.00",
        image: "images/luzon/luzon7.jpg",
        href: "properties/luzon7.html",
    },
    {
        title: "2BR Prime House & Lot",
        floorArea: "200sqm",
        lotArea: "100sqm",
        location: "Lipa, Batangas",
        price: "Php 4,450,000.00",
        image: "images/luzon/luzon8.jpg",
        href: "properties/luzon8.html",
    },
    {
        title: "2BR Corner House & Lot",
        floorArea: "250sqm",
        lotArea: "150sqm",
        location: "Sta. Rosa, Laguna",
        price: "Php 7,450,000.00",
        image: "images/luzon/luzon9.jpg",
        href: "properties/luzon9.html",
    },
    {
        title: "1BR Single-Attached House & Lot",
        floorArea: "45sqm",
        lotArea: "70sqm",
        location: "San Jose del Monte, Bulacan",
        price: "Php 2,150,000.00",
        image: "images/luzon/luzon10.jpg",
        href: "properties/luzon10.html",
    },
    {
        title: "1BR Condominium",
        floorArea: "50sqm",
        lotArea: "N/A",
        location: "San Fernando, Pampanga",
        price: "Php 3,450,000.00",
        image: "images/luzon/luzon11.jpg",
        href: "properties/luzon11.html",
    },
    {
        title: "1BR Prime Condominium",
        floorArea: "40sqm",
        lotArea: "N/A",
        location: "Pasay City, Metro Manila",
        price: "Php 6,450,000.00",
        image: "images/luzon/luzon12.jpg",
        href: "properties/luzon1.html",
    },
];

const visayas = [
    {
        title: "3BR Prime House & Lot",
        floorArea: "400sqm",
        lotArea: "300sqm",
        location: "Bacolod, Negros Occidental",
        price: "Php 9,450,000.00",
        image: "images/visayas/visayas1.jpg",
        href: "properties/visayas1.html",
    },
    {
        title: "2BR Single-Attached House & Lot",
        floorArea: "250sqm",
        lotArea: "150sqm",
        location: "Baybay, Leyte",
        price: "Php 3,250,000.00",
        image: "images/visayas/visayas2.jpg",
        href: "properties/visayas2.html",
    },
    {
        title: "2BR 2-storey House & Lot",
        floorArea: "300sqm",
        lotArea: "250sqm",
        location: "Carcar, Cebu",
        price: "Php 5,150,000.00",
        image: "images/visayas/visayas3.jpg",
        href: "properties/visayas3.html",
    },
    {
        title: "2BR House & Lot",
        floorArea: "250sqm",
        lotArea: "150sqm",
        location: "Dumaguete, Negros Oriental",
        price: "Php 4,000,000.00",
        image: "images/visayas/visayas4.jpg",
        href: "properties/visayas4.html",
    },
    {
        title: "2BR House & Lot",
        floorArea: "260sqm",
        lotArea: "175sqm",
        location: "Iloilo, Iloilo",
        price: "Php 3,299,000.00",
        image: "images/visayas/visayas5.jpg",
        href: "properties/visayas5.html",
    },
    {
        title: "1BR Loft-type Condominium",
        floorArea: "50sqm",
        lotArea: "N/A",
        location: "Naga, Cebu",
        price: "Php 4,450,000.00",
        image: "images/visayas/visayas6.jpg",
        href: "properties/visayas6.html",
    },
    {
        title: "Studio Type Condominium",
        floorArea: "60sqm",
        lotArea: "N/A",
        location: "San Carlos, Negros Occidental",
        price: "Php 3,950,000.00",
        image: "images/visayas/visayas7.jpg",
        href: "properties/visayas7.html",
    },
    {
        title: "2Studio Type Condominium",
        floorArea: "40sqm",
        lotArea: "N/A",
        location: "Tacloban, Leyte",
        price: "Php 3,150,000.00",
        image: "images/visayas/visayas8.jpg",
        href: "properties/visayas8.html",
    },
    {
        title: "2BR House & Lot",
        floorArea: "250sqm",
        lotArea: "150sqm",
        location: "Talisay, Negros Occidental",
        price: "Php 5,450,000.00",
        image: "images/visayas/visayas9.jpg",
        href: "properties/visayas9.html",
    },
    {
        title: "2BR Single-Attached House & Lot",
        floorArea: "200sqm",
        lotArea: "125sqm",
        location: "Toledo, Cebu",
        price: "Php 3,150,000.00",
        image: "images/visayas/visayas10.jpg",
        href: "properties/visayas10.html",
    },
    {
        title: "2BR Modern-style House & Lot",
        floorArea: "150sqm",
        lotArea: "120sqm",
        location: "La Carlota, Negros Occidental",
        price: "Php 4,450,000.00",
        image: "images/visayas/visayas11.jpg",
        href: "properties/visayas11.html",
    },
    {
        title: "1BR Prime Condominium",
        floorArea: "60sqm",
        lotArea: "N/A",
        location: "Cebu City, Cebu",
        price: "Php 4,450,000.00",
        image: "images/visayas/visayas12.jpg",
        href: "properties/visayas12.html",
    },
];

const mindanao = [
    {
        title: "3BR Prime House & Lot",
        floorArea: "400sqm",
        lotArea: "300sqm",
        location: "Butuan, Agusan del Norte",
        price: "Php 9,450,000.00",
        image: "images/mindanao/mindanao1.jpg",
        href: "properties/mindanao1.html",
    },
    {
        title: "2BR Single-Attached House & Lot",
        floorArea: "250sqm",
        lotArea: "150sqm",
        location: "Bayugan, Agusan del Sur",
        price: "Php 3,250,000.00",
        image: "images/mindanao/mindanao2.jpg",
        href: "properties/mindanao2.html",
    },
    {
        title: "2BR 2-storey House & Lot",
        floorArea: "150sqm",
        lotArea: "60sqm",
        location: "Malaybalay, Bukidnon",
        price: "Php 2,550,000.00",
        image: "images/mindanao/mindanao3.jpg",
        href: "properties/mindanao3.html",
    },
    {
        title: "2BR House & Lot",
        floorArea: "250sqm",
        lotArea: "150sqm",
        location: "City of Isabela",
        price: "Php 3,500,000.00",
        image: "images/mindanao/mindanao4.jpg",
        href: "properties/mindanao4.html",
    },
    {
        title: "3BR Prime House & Lot",
        floorArea: "360sqm",
        lotArea: "250sqm",
        location: "Cotabato City",
        price: "Php 9,299,000.00",
        image: "images/mindanao/mindanao5.jpg",
        href: "properties/mindanao5.html",
    },
    {
        title: "2BR House & Lot",
        floorArea: "190sqm",
        lotArea: "220sqm",
        location: "Panabo, Davao del Norte",
        price: "Php 2,450,000.00",
        image: "images/mindanao/mindanao6.jpg",
        href: "properties/mindanao6.html",
    },
    {
        title: "3BR Modern-style House & Lot",
        floorArea: "250sqm",
        lotArea: "350sqm",
        location: "Tagun, Davao del Norte",
        price: "Php 3,950,000.00",
        image: "images/mindanao/mindanao7.jpg",
        href: "properties/mindanao7.html",
    },
    {
        title: "2BR Single-attached House & Lot",
        floorArea: "140sqm",
        lotArea: "110sqm",
        location: "Davao City, Davao del Sur",
        price: "Php 3,150,000.00",
        image: "images/mindanao/mindanao8.jpg",
        href: "properties/mindanao8.html",
    },
    {
        title: "2BR House & Lot",
        floorArea: "150sqm",
        lotArea: "70sqm",
        location: "Mati, Davao Oriental",
        price: "Php 2,450,000.00",
        image: "images/mindanao/mindanao9.jpg",
        href: "properties/mindanao9.html",
    },
    {
        title: "2BR Single-Attached House & Lot",
        floorArea: "200sqm",
        lotArea: "125sqm",
        location: "Tacurong, Sultan Kudarat",
        price: "Php 4,150,000.00",
        image: "images/mindanao/mindanao10.jpg",
        href: "properties/mindanao10.html",
    },
    {
        title: "2BR Modern-style House & Lot",
        floorArea: "120sqm",
        lotArea: "60sqm",
        location: "Surigao City, Surigao del Norte",
        price: "Php 2,750,000.00",
        image: "images/mindanao/mindanao11.jpg",
        href: "properties/mindanao11.html",
    },
    {
        title: "2BR Bungalow House & Lot",
        floorArea: "120sqm",
        lotArea: "160sqm",
        location: "Dapitan, Zamboanga del Norte",
        price: "Php 4,450,000.00",
        image: "images/mindanao/mindanao12.jpg",
        href: "properties/mindanao12.html",
    },
];

const showProperty = (property) => {
    document.querySelector("#show-property img").src = `../${property.image}`;
    document.querySelector("#show-property #title").innerText = property.title;
    document.querySelector("#show-property #price").innerText = property.price;
    document.querySelector("#show-property #location").innerText = `Location: ${property.location}`;
    document.querySelector("#show-property #floor-area").innerText = `Floor Area: ${property.floorArea}`;
    document.querySelector("#show-property #lot-area").innerText = `Lot Area: ${property.lotArea}`;
};
